services:
  postgres:
    image: postgres:latest
    container_name: crud_api1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: user_db
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
      
networks:
  nest_network:
    driver: bridge

volumes:
  postgres_data:
